"""GeoKG 行政区划数据 — 全球 ISO 3166-2 一级行政区（补充集）。

数据说明：按各国官方一级行政区（省/州/大区/郡）名称整理。
与 reference_data.ADMIN1_REGIONS 和 gazetteer.ADMIN1_EXTENDED 合并后
覆盖全球主要国家。
"""

from __future__ import annotations

#: ISO 3166-1 alpha-3 → 一级行政区名称列表
ADMIN1_GLOBAL: dict[str, list[str]] = {
    # ── 欧洲 ──
    "ALB": ["Berat","Dibër","Durrës","Elbasan","Fier","Gjirokastër","Korçë","Kukës",
            "Lezhë","Shkodër","Tirana","Vlorë"],
    "AND": ["Andorra la Vella","Canillo","Encamp","Escaldes-Engordany","La Massana",
            "Ordino","Sant Julià de Lòria"],
    "AUT": ["Burgenland","Kärnten","Niederösterreich","Oberösterreich","Salzburg",
            "Steiermark","Tirol","Vorarlberg","Wien"],
    "BEL": ["Antwerpen","Bruxelles-Capitale","Hainaut","Liège","Limburg","Luxembourg",
            "Namur","Oost-Vlaanderen","Vlaams-Brabant","Waals-Brabant","West-Vlaanderen"],
    "BIH": ["Brčko","Federacija Bosne i Hercegovine","Republika Srpska"],
    "BGR": ["Blagoevgrad","Burgas","Dobrich","Gabrovo","Haskovo","Kardzhali","Kyustendil",
            "Lovech","Montana","Pazardzhik","Pernik","Pleven","Plovdiv","Razgrad","Ruse",
            "Shumen","Silistra","Sliven","Smolyan","Sofia","Sofia City","Stara Zagora",
            "Targovishte","Varna","Veliko Tarnovo","Vidin","Vratsa","Yambol"],
    "BLR": ["Brest","Gomel","Grodno","Minsk","Minsk City","Mogilev","Vitebsk"],
    "CHE": ["Aargau","Appenzell Ausserrhoden","Appenzell Innerrhoden","Basel-Landschaft",
            "Basel-Stadt","Bern","Fribourg","Genève","Glarus","Graubünden","Jura","Luzern",
            "Neuchâtel","Nidwalden","Obwalden","Schaffhausen","Schwyz","Solothurn","St. Gallen",
            "Thurgau","Ticino","Uri","Valais","Vaud","Zug","Zürich"],
    "CYP": ["Famagusta","Kyrenia","Larnaca","Limassol","Nicosia","Paphos"],
    "CZE": ["Hlavní město Praha","Jihočeský","Jihomoravský","Karlovarský","Královéhradecký",
            "Liberecký","Moravskoslezský","Olomoucký","Pardubický","Plzeňský","Středočeský",
            "Ústecký","Vysočina","Zlínský"],
    "DNK": ["Hovedstaden","Midtjylland","Nordjylland","Sjælland","Syddanmark"],
    "ESP": ["Andalucía","Aragón","Asturias","Cantabria","Castilla-La Mancha","Castilla y León",
            "Cataluña","Ceuta","Comunidad Valenciana","Extremadura","Galicia","Islas Baleares",
            "Islas Canarias","La Rioja","Madrid","Melilla","Murcia","Navarra","País Vasco"],
    "EST": ["Harju","Hiiu","Ida-Viru","Järva","Jõgeva","Lääne","Lääne-Viru","Põlva","Pärnu",
            "Rapla","Saare","Tartu","Valga","Viljandi","Võru"],
    "FIN": ["Ahvenanmaa","Etelä-Karjala","Etelä-Pohjanmaa","Etelä-Savo","Kainuu",
            "Kanta-Häme","Keski-Pohjanmaa","Keski-Suomi","Kymenlaakso","Lappi","Pirkanmaa",
            "Pohjanmaa","Pohjois-Karjala","Pohjois-Pohjanmaa","Pohjois-Savo","Päijät-Häme",
            "Satakunta","Uusimaa","Varsinais-Suomi"],
    "FRO": ["Borðoy","Eysturoy","Sandoy","Streymoy","Suðuroy","Vágar"],
    "GRC": ["Anatoliki Makedonia","Attiki","Dytiki Ellada","Dytiki Makedonia","Ionia Nisia",
            "Ipeiros","Kentriki Makedonia","Kriti","Notio Aigaio","Peloponnisos",
            "Sterea Ellada","Thessalia","Voreio Aigaio"],
    "HRV": ["Bjelovarsko-bilogorska","Brodsko-posavska","Dubrovačko-neretvanska","Grad Zagreb",
            "Istarska","Karlovačka","Koprivničko-križevačka","Krapinsko-zagorska","Ličko-senjska",
            "Međimurska","Osječko-baranjska","Požeško-slavonska","Primorsko-goranska",
            "Sisačko-moslavačka","Splitsko-dalmatinska","Šibensko-kninska","Varaždinska",
            "Virovitičko-podravska","Vukovarsko-srijemska","Zadarska","Zagrebačka"],
    "HUN": ["Bács-Kiskun","Baranya","Békés","Borsod-Abaúj-Zemplén","Budapest","Csongrád-Csanád",
            "Fejér","Győr-Moson-Sopron","Hajdú-Bihar","Heves","Jász-Nagykun-Szolnok",
            "Komárom-Esztergom","Nógrád","Pest","Somogy","Szabolcs-Szatmár-Bereg","Tolna",
            "Vas","Veszprém","Zala"],
    "IRL": ["Carlow","Cavan","Clare","Cork","Donegal","Dublin","Galway","Kerry","Kildare",
            "Kilkenny","Laois","Leitrim","Limerick","Longford","Louth","Mayo","Meath",
            "Monaghan","Offaly","Roscommon","Sligo","Tipperary","Waterford","Westmeath",
            "Wexford","Wicklow"],
    "ISL": ["Austurland","Höfuðborgarsvæði","Norðurland eystra","Norðurland vestra",
            "Suðurland","Suðurnes","Vestfirðir","Vesturland"],
    "ITA": ["Abruzzo","Basilicata","Calabria","Campania","Emilia-Romagna","Friuli-Venezia Giulia",
            "Lazio","Liguria","Lombardia","Marche","Molise","Piemonte","Puglia","Sardegna",
            "Sicilia","Toscana","Trentino-Alto Adige","Umbria","Valle d'Aosta","Veneto"],
    "LIE": ["Balzers","Eschen","Gamprin","Mauren","Planken","Ruggell","Schaan","Schellenberg",
            "Triesen","Triesenberg","Vaduz"],
    "LTU": ["Alytus","Kaunas","Klaipėda","Marijampolė","Panevėžys","Šiauliai","Tauragė",
            "Telšiai","Utena","Vilnius"],
    "LUX": ["Capellen","Clervaux","Diekirch","Echternach","Esch-sur-Alzette","Grevenmacher",
            "Luxembourg","Mersch","Redange","Remich","Vianden","Wiltz"],
    "LVA": ["Daugavpils","Jelgava","Jūrmala","Liepāja","Rēzekne","Rīga","Ventspils",
            "Ādaži","Aizkraukle","Alūksne","Balvi","Bauska","Cēsis","Dobele","Gulbene",
            "Jēkabpils","Krāslava","Kuldīga","Limbaži","Līvāni","Ludza","Madona","Ogre",
            "Preiļi","Saldus","Saulkrasti","Sigulda","Smiltene","Talsi","Tukums","Valka","Valmiera","Varakļāni"],
    "MDA": ["Anenii Noi","Bălți","Basarabeasca","Bender","Briceni","Cahul","Călărași","Cantemir",
            "Căușeni","Chișinău","Cimișlia","Criuleni","Dondușeni","Drochia","Dubăsari","Edineț",
            "Fălești","Florești","Gagauzia","Glodeni","Hîncești","Ialoveni","Leova","Nisporeni",
            "Ocnița","Orhei","Rezina","Rîșcani","Sîngerei","Soroca","Șoldănești","Ștefan Vodi",
            "Strășeni","Taraclia","Telenești","Transnistria","Ungheni"],
    "MKD": ["Aerodrom","Aračinovo","Berovo","Bitola","Bogdanci","Bogovinje","Bosilovo",
            "Brvenica","Butel","Čair","Čaška","Centar","Centar Župa","Češinovo-Obleševo",
            "Čučer-Sandevo","Debar","Debarca","Delčevo","Demir Hisar","Demir Kapija","Dojran",
            "Dolneni","Drugovo","Gazi Baba","Gevgelija","Gostivar","Gradsko","Ilinden","Jegunovce",
            "Karbinci","Karpoš","Kavadarci","Kičevo","Kisela Voda","Kočani","Konče","Kratovo",
            "Kriva Palanka","Krivogaštani","Kruševo","Kumanovo","Lipkovo","Lozovo","Makedonska Kamenica",
            "Makedonski Brod","Mavrovo i Rostuša","Mogila","Negotino","Novaci","Novo Selo","Ohrid",
            "Pehčevo","Petrovec","Plasnica","Prilep","Probištip","Radoviš","Rankovce","Resen",
            "Rosoman","Saraj","Sopište","Staro Nagoričane","Štip","Struga","Strumica","Studeničani",
            "Šuto Orizari","Sveti Nikole","Tearce","Tetovo","Valandovo","Vasilevo","Veles","Vevčani",
            "Vinica","Vraneštica","Vrapčište","Zajas","Zelenikovo","Želino","Zrnovci"],
    "MNE": ["Andrijevica","Bar","Berane","Bijelo Polje","Budva","Cetinje","Danilovgrad",
            "Gusinje","Herceg Novi","Kolašin","Kotor","Mojkovac","Nikšić","Petnjica","Plav",
            "Pljevlja","Plužine","Podgorica","Rožaje","Šavnik","Tivat","Tuzi","Ulcinj","Žabljak"],
    "NLD": ["Drenthe","Flevoland","Friesland","Gelderland","Groningen","Limburg",
            "Noord-Brabant","Noord-Holland","Overijssel","Utrecht","Zeeland","Zuid-Holland"],
    "NOR": ["Agder","Akershus","Buskerud","Finnmark","Innlandet","Møre og Romsdal","Nordland",
            "Oslo","Rogaland","Telemark","Troms","Trøndelag","Vestfold","Vestland","Østfold"],
    "POL": ["Dolnośląskie","Kujawsko-Pomorskie","Lubelskie","Lubuskie","Łódzkie","Małopolskie",
            "Mazowieckie","Opolskie","Podkarpackie","Podlaskie","Pomorskie","Śląskie",
            "Świętokrzyskie","Warmińsko-Mazurskie","Wielkopolskie","Zachodniopomorskie"],
    "PRT": ["Aveiro","Açores","Beja","Braga","Bragança","Castelo Branco","Coimbra","Évora",
            "Faro","Guarda","Leiria","Lisboa","Madeira","Portalegre","Porto","Santarém",
            "Setúbal","Viana do Castelo","Vila Real","Viseu"],
    "ROU": ["Alba","Arad","Argeș","Bacău","Bihor","Bistrița-Năsăud","Botoșani","Brașov",
            "Brăila","București","Buzău","Caraș-Severin","Călărași","Cluj","Constanța",
            "Covasna","Dâmbovița","Dolj","Galați","Giurgiu","Gorj","Harghita","Hunedoara",
            "Ialomița","Iași","Ilfov","Maramureș","Mehedinți","Mureș","Neamț","Olt","Prahova",
            "Satu Mare","Sălaj","Sibiu","Suceava","Teleorman","Timiș","Tulcea","Vaslui","Vâlcea","Vrancea"],
    "SRB": ["Beograd","Bor","Braničevo","Jablanica","Kolubara","Mačva","Moravica","Nišava",
            "Pčinja","Pirot","Podunavlje","Pomoravlje","Rasina","Raška","Šumadija","Toplica",
            "Zaječar","Zlatibor","Južni Banat","Južna Bačka","Severni Banat","Severna Bačka",
            "Srednji Banat","Srem","Zapadna Bačka","Kosovo","Kosovo-Pomoravlje","Kosovska Mitrovica",
            "Peć","Prizren"],
    "SVK": ["Banskobystrický","Bratislavský","Košický","Nitriansky","Prešovský","Trenčiansky",
            "Trnavský","Žilinský"],
    "SVN": ["Ajdovščina","Beltinci","Bled","Bohinj","Borovnica","Bovec","Brda","Brezovica",
            "Brežice","Cankova","Celje","Cerklje na Gorenjskem","Cerknica","Cerkno","Črenšovci",
            "Črna na Koroškem","Črnomelj","Destrnik","Divača","Dobrepolje","Dobrova-Polhov Gradec",
            "Dol pri Ljubljani","Dolenjske Toplice","Domžale","Dornava","Dravograd","Duplek",
            "Gorenja vas-Poljane","Gorišnica","Gornja Radgona","Gornji Grad","Gornji Petrovci",
            "Grosuplje","Hajdina","Hoče-Slivnica","Hodoš","Horjul","Hrastnik","Hrpelje-Kozina",
            "Idrija","Ig","Ilirska Bistrica","Ivančna Gorica","Izola","Jesenice","Jezerce",
            "Juršinci","Kamnik","Kanal","Kidričevo","Kobarid","Kobilje","Kočevje","Komen",
            "Komenda","Koper","Kostanjevica na Krki","Kostel","Kozje","Kranj","Kranjska Gora",
            "Križevci","Krško","Kungota","Kuzma","Laško","Lenart","Lendava","Litija","Ljubljana",
            "Ljubno","Ljutomer","Logatec","Loška dolina","Loški Potok","Lovrenc na Pohorju",
            "Luče","Lukovica","Majšperk","Maribor","Markovci","Medvode","Mengeš","Metlika",
            "Mežica","Miren-Kostanjevica","Mirna Peč","Mislinja","Moravče","Moravske Toplice",
            "Mozirje","Murska Sobota","Muta","Naklo","Nazarje","Nova Gorica","Novo Mesto","Odranci",
            "Oplotnica","Ormož","Osilnica","Pesnica","Piran","Pivka","Podčetrtek","Podlehnik",
            "Podvelka","Postojna","Preddvor","Prevalje","Ptuj","Puconci","Rače-Fram","Radeče",
            "Radenci","Radlje ob Dravi","Radovljica","Ravne na Koroškem","Razkrižje","Ribnica",
            "Ribnica na Pohorju","Rogaška Slatina","Rogašovci","Rogatec","Ruše","Selnica ob Dravi",
            "Semič","Sevnica","Sežana","Slovenj Gradec","Slovenska Bistrica","Slovenske Konjice",
            "Šmarje pri Jelšah","Šmartno ob Paki","Šoštanj","Starše","Štore","Sveti Jurij",
            "Tolmin","Trbovlje","Trebnje","Tržič","Turnišče","Velenje","Velike Lašče","Videm",
            "Vipava","Vitanje","Vodice","Vojnik","Vrhnika","Vuzenica","Zagorje ob Savi",
            "Zavrč","Zreče","Žalec","Železniki","Žiri","Žirovnica"],
    "SWE": ["Blekinge","Dalarna","Gotland","Gävleborg","Halland","Jämtland","Jönköping",
            "Kalmar","Kronoberg","Norrbotten","Skåne","Stockholm","Södermanland","Uppsala",
            "Värmland","Västerbotten","Västernorrland","Västmanland","Västra Götaland",
            "Örebro","Östergötland"],

    # ── 非洲 ──
    "BDI": ["Bubanza","Bujumbura Mairie","Bujumbura Rural","Bururi","Cankuzo","Cibitoke",
            "Gitega","Karuzi","Kayanza","Kirundo","Makamba","Muramvya","Muyinga","Mwaro",
            "Ngozi","Rumonge","Rutana","Ruyigi"],
    "BEN": ["Alibori","Atacora","Atlantique","Borgou","Collines","Couffo","Donga","Littoral",
            "Mono","Ouémé","Plateau","Zou"],
    "BWA": ["Central","Chobe","Ghanzi","Kgalagadi","Kgatleng","Kweneng","North East",
            "North West","South East","Southern"],
    "CAF": ["Bamingui-Bangoran","Bangui","Basse-Kotto","Haute-Kotto","Haut-Mbomou","Kémo",
            "Lobaye","Mambéré-Kadéï","Mbomou","Nana-Grébizi","Nana-Mambéré","Ombella-M'Poko",
            "Ouaka","Ouham","Ouham-Pendé","Sangha-Mbaéré","Vakaga"],
    "COM": ["Anjouan","Grande Comore","Mohéli"],
    "CPV": ["Boa Vista","Brava","Maio","Mosteiros","Paul","Porto Novo","Praia","Ribeira Brava",
            "Ribeira Grande","Ribeira Grande de Santiago","Sal","Santa Catarina","Santa Catarina do Fogo",
            "Santa Cruz","São Domingos","São Filipe","São Lourenço dos Órgãos","São Miguel",
            "São Salvador do Mundo","São Vicente","Tarrafal","Tarrafal de São Nicolau"],
    "DJI": ["Ali Sabieh","Arta","Dikhil","Djibouti","Obock","Tadjourah"],
    "ERI": ["Anseba","Debub","Debubawi Keyih Bahri","Gash-Barka","Maekel","Semenawi Keyih Bahri"],
    "GMB": ["Banjul","Central River","Lower River","North Bank","Upper River","West Coast"],
    "GNB": ["Bafatá","Biombo","Bissau","Bolama","Cacheu","Gabú","Oio","Quinara","Tombali"],
    "GNQ": ["Annobón","Bioko Norte","Bioko Sur","Centro Sur","Djibloho","Kié-Ntem","Litoral",
            "Wele-Nzas"],
    "LSO": ["Berea","Butha-Buthe","Leribe","Mafeteng","Maseru","Mohale's Hoek","Mokhotlong",
            "Qacha's Nek","Quthing","Thaba-Tseka"],
    "MDG": ["Alaotra-Mangoro","Amoron'i Mania","Analamanga","Analanjirofo","Androy","Anosy",
            "Atsimo-Andrefana","Atsimo-Atsinanana","Atsinanana","Betsiboka","Boeny","Bongolava",
            "Diana","Fitovinany","Haute Matsiatra","Ihorombe","Itasy","Melaky","Menabe",
            "Sava","Sofia","Vakinankaratra","Vatovavy"],
    "MRT": ["Adrar","Assaba","Brakna","Dakhlet Nouadhibou","Gorgol","Guidimaka","Hodh Ech Chargui",
            "Hodh El Gharbi","Inchiri","Nouakchott Nord","Nouakchott Ouest","Nouakchott Sud",
            "Tagant","Tiris Zemmour","Trarza"],
    "MUS": ["Black River","Flacq","Grand Port","Moka","Pamplemousses","Plaines Wilhems",
            "Port Louis","Rivière du Rempart","Savanne"],
    "NAM": ["Erongo","Hardap","Karas","Kavango East","Kavango West","Khomas","Kunene",
            "Ohangwena","Omaheke","Omusati","Oshana","Oshikoto","Otjozondjupa","Zambezi"],
    "SDN": ["Al Jazirah","Al Qadarif","Blue Nile","Central Darfur","East Darfur","Kassala",
            "Khartoum","North Darfur","North Kordofan","Northern","Red Sea","River Nile",
            "Sennar","South Darfur","South Kordofan","West Darfur","West Kordofan","White Nile"],
    "SOM": ["Awdal","Bakool","Banaadir","Bari","Bay","Galguduud","Gedo","Hiiraan","Jubbada Dhexe",
            "Jubbada Hoose","Mudug","Nugaal","Sanaag","Shabeellaha Dhexe","Shabeellaha Hoose",
            "Sool","Togdheer","Woqooyi Galbeed"],
    "SSD": ["Central Equatoria","Eastern Equatoria","Jonglei","Lakes","Northern Bahr el Ghazal",
            "Unity","Upper Nile","Warrap","Western Bahr el Ghazal","Western Equatoria"],
    "STP": ["Príncipe","São Tomé"],
    "SWZ": ["Hhohho","Lubombo","Manzini","Shiselweni"],
    "SYC": ["Anse Boileau","Anse Etoile","Anse Royale","Au Cap","Baie Lazare","Baie Sainte Anne",
            "Beau Vallon","Bel Air","Bel Ombre","Cascade","Glacis","Grand Anse Mahe",
            "Grand Anse Praslin","La Digue","La Riviere Anglaise","Les Mamelles","Mont Buxton",
            "Mont Fleuri","Plaisance","Pointe Larue","Port Glaud","Roche Caiman","Saint Louis",
            "Takamaka"],
    "TGO": ["Centrale","Kara","Maritime","Plateaux","Savanes"],

    # ── 美洲 ──
    "ATG": ["Barbuda","Redonda","Saint George","Saint John","Saint Mary","Saint Paul","Saint Peter","Saint Philip"],
    "BHS": ["Abaco","Acklins","Andros","Berry Islands","Bimini","Black Point","Cat Island",
            "Central Abaco","Central Andros","Central Eleuthera","City of Freeport","Crooked Island",
            "East Grand Bahama","Exuma","Grand Cay","Harbour Island","Hope Town","Inagua",
            "Long Island","Mangrove Cay","Mayaguana","Moore's Island","North Abaco","North Andros",
            "North Eleuthera","Ragged Island","Rum Cay","San Salvador","South Abaco","South Andros",
            "South Eleuthera","Spanish Wells","West Grand Bahama"],
    "BRB": ["Christ Church","Saint Andrew","Saint George","Saint James","Saint John","Saint Joseph",
            "Saint Lucy","Saint Michael","Saint Peter","Saint Philip","Saint Thomas"],
    "DMA": ["Saint Andrew","Saint David","Saint George","Saint John","Saint Joseph","Saint Luke",
            "Saint Mark","Saint Patrick","Saint Paul","Saint Peter"],
    "GRD": ["Saint Andrew","Saint David","Saint George","Saint John","Saint Mark","Saint Patrick"],
    "GRL": ["Avannaata","Kujalleq","Qeqertalik","Qeqqata","Sermersooq"],
    "KNA": ["Christ Church Nichola Town","Saint Anne Sandy Point","Saint George Basseterre",
            "Saint George Gingerland","Saint James Windward","Saint John Capisterre",
            "Saint John Figtree","Saint Kitts","Saint Mary Cayon","Saint Paul Capisterre",
            "Saint Paul Charlestown","Saint Peter Basseterre","Saint Thomas Lowland",
            "Saint Thomas Middle Island","Trinity Palmetto Point","Nevis"],
    "LCA": ["Anse la Raye","Canaries","Castries","Choiseul","Dennery","Gros Islet","Laborie",
            "Micoud","Soufrière","Vieux Fort"],
    "PRI": ["Adjuntas","Aguada","Aguadilla","Aguas Buenas","Aibonito","Añasco","Arecibo",
            "Arroyo","Barceloneta","Barranquitas","Bayamón","Cabo Rojo","Caguas","Camuy",
            "Canóvanas","Carolina","Cataño","Cayey","Ceiba","Ciales","Cidra","Coamo","Comerío",
            "Corozal","Culebra","Dorado","Fajardo","Florida","Guánica","Guayama","Guayanilla",
            "Guaynabo","Gurabo","Hatillo","Hormigueros","Humacao","Isabela","Jayuya","Juana Díaz",
            "Juncos","Lajas","Lares","Las Marías","Las Piedras","Loíza","Luquillo","Manatí",
            "Maricao","Maunabo","Mayagüez","Moca","Morovis","Naguabo","Naranjito","Orocovis",
            "Patillas","Peñuelas","Ponce","Quebradillas","Rincón","Río Grande","Sabana Grande",
            "Salinas","San Germán","San Juan","San Lorenzo","San Sebastián","Santa Isabel",
            "Toa Alta","Toa Baja","Trujillo Alto","Utuado","Vega Alta","Vega Baja","Vieques",
            "Villalba","Yabucoa","Yauco"],
    "VCT": ["Charlotte","Grenadines","Saint Andrew","Saint David","Saint George","Saint Patrick"],

    # ── 亚洲 ──
    "PSE": ["Bethlehem","Deir al-Balah","Gaza","Hebron","Jenin","Jericho","Jerusalem",
            "Khan Yunis","Nablus","North Gaza","Qalqilya","Rafah","Ramallah and al-Bireh",
            "Salfit","Tubas","Tulkarm"],

    # ── 大洋洲 ──
    "COK": ["Aitutaki","Atiu","Avarua","Mangaia","Manihiki","Mauke","Mitiaro","Palmerston",
            "Penrhyn","Pukapuka","Rakahanga","Rarotonga"],
    "FJI": ["Ba","Bua","Cakaudrove","Kadavu","Lau","Lomaiviti","Macuata","Nadroga-Navosa",
            "Naitasiri","Namosi","Ra","Rewa","Serua","Tailevu"],
    "FSM": ["Chuuk","Kosrae","Pohnpei","Yap"],
    "KIR": ["Banaba","Central Gilberts","Line Islands","Northern Gilberts","Southern Gilberts",
            "Tarawa"],
    "MHL": ["Ailinglaplap","Ailuk","Arno","Aur","Ebon","Enewetak","Jabat","Jaluit","Kili",
            "Kwajalein","Lae","Lib","Likiep","Majuro","Maloelap","Mejit","Mili","Namdrik",
            "Namu","Rongelap","Ujae","Utirik","Wotho","Wotje"],
    "NCL": ["Îles Loyauté","Nord","Sud"],
    "NIU": ["Alofi North","Alofi South","Avatele","Hakupu","Hikutavake","Lakepa","Liku",
            "Makefu","Mutalau","Namukulu","Tamakautoga","Toi","Tuapa","Vaiea"],
    "PLW": ["Aimeliik","Airai","Angaur","Hatohobei","Kayangel","Koror","Melekeok","Ngaraard",
            "Ngarchelong","Ngardmau","Ngatpang","Ngchesar","Ngeremlengui","Ngiwal","Peleliu","Sonsorol"],
    "PYF": ["Îles Australes","Îles du Vent","Îles Marquises","Îles Sous-le-Vent","Îles Tuamotu-Gambier"],
    "SLB": ["Central","Choiseul","Guadalcanal","Honiara","Isabel","Makira-Ulawa","Malaita",
            "Rennell and Bellona","Temotu","Western"],
    "TON": ["Haʻapai","Ongo Niua","Tongatapu","Vavaʻu","ʻEua"],
    "TUV": ["Funafuti","Nanumanga","Nanumea","Niutao","Nui","Nukufetau","Nukulaelae","Vaitupu"],
    "VUT": ["Malampa","Penama","Sanma","Shefa","Tafea","Torba"],
    "WSM": ["A'ana","Aiga-i-le-Tai","Atua","Fa'asaleleaga","Gaga'emauga","Gaga'ifomauga",
            "Palauli","Satupa'itea","Tuamasaga","Va'a-o-Fonoti","Vaisigano"],
    "WLF": ["Alo","Sigave","Uvea"],
}


def global_admin1_stats() -> dict[str, int]:
    """返回补充行政区数据统计。"""
    return {
        "countries": len(ADMIN1_GLOBAL),
        "regions": sum(len(v) for v in ADMIN1_GLOBAL.values()),
    }